#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

service_link_enhanced("memcached", "S55", "7");
service_link_enhanced("sogod", "S85", "7");

templates2events("/etc/e-smith/sql/init/30sogo_mysql_create_database", qw(post-upgrade post-install bootstrap-console-save));
templates2events("/etc/e-smith/sql/init/31sogo_mysql_update_privileges", qw(post-upgrade post-install bootstrap-console-save));
templates2events("/var/lib/sogo/smeserver/sogo_mysql_update_privileges.sql", qw(post-upgrade post-install bootstrap-console-save));

templates2events("/etc/e-smith/sql/init/31sogo_upgrade", qw(post-upgrade post-install post-upgrade));

templates2events("/etc/httpd/conf/httpd.conf", qw(post-upgrade sogo-modify));
templates2events("/etc/sogo/sogo.conf", qw(post-upgrade sogo-modify bootstrap-console-save));
templates2events("/etc/sysconfig/memcached", qw(post-upgrade sogo-modify bootstrap-console-save));
templates2events("/etc/logrotate.d/sogo", qw(post-upgrade sogo-modify bootstrap-console-save));
templates2events("/etc/sysconfig/sogo", qw(post-upgrade sogo-modify bootstrap-console-save));
templates2events("/etc/rc.d/init.d/masq",qw(post-upgrade sogo-modify));
templates2events("/etc/cron.d/sogo",qw(post-upgrade sogo-modify));
templates2events("/etc/dovecot/master.users",qw(post-upgrade sogo-modify));

safe_symlink("sigusr1", "root/etc/e-smith/events/sogo-modify/services2adjust/httpd-e-smith");
safe_symlink("restart", "root/etc/e-smith/events/sogo-modify/services2adjust/sogod");
safe_symlink("restart", "root/etc/e-smith/events/sogo-modify/services2adjust/dovecot");
safe_symlink("restart", "root/etc/e-smith/events/sogo-modify/services2adjust/memcached");
safe_symlink("adjust", "root/etc/e-smith/events/sogo-modify/services2adjust/masq");

for my $event (qw(pre-backup))
{
    event_link("sogo-backup", $event, "80");
}

