#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

service_link_enhanced("memcached", "S55", "7");
service_link_enhanced("sogod", "S85", "7");

templates2events("/etc/e-smith/sql/init/30sogo_mysql_create_database", qw(sogo-modify post-install bootstrap-console-save));
templates2events("/etc/e-smith/sql/init/31sogo_mysql_update_privileges", qw(sogo-modify post-install bootstrap-console-save));
templates2events("/etc/e-smith/sql/init/31sogo_upgrade", qw(sogo-modify post-install post-upgrade));
templates2events("/etc/e-smith/sql/init/32sogo_upgrade_2.3", qw(sogo-modify post-install post-upgrade));

templates2events("/var/lib/sogo/smeserver/sogo_mysql_update_privileges.sql", qw(sogo-modify post-install bootstrap-console-save));

templates2events("/var/service/tinydns/root/data", qw( email-update sogo-modify));
templates2events("/etc/httpd/conf/httpd.conf", qw( email-update sogo-modify));
templates2events("/etc/sogo/sogo.conf", qw( email-update sogo-modify bootstrap-console-save));
templates2events("/etc/sysconfig/memcached", qw( email-update sogo-modify bootstrap-console-save));
templates2events("/etc/logrotate.d/sogo", qw( email-update sogo-modify bootstrap-console-save));
templates2events("/etc/sysconfig/sogo", qw( email-update sogo-modify bootstrap-console-save));
templates2events("/etc/rc.d/init.d/masq",qw( email-update sogo-modify));
templates2events("/etc/cron.d/sogo",qw( email-update sogo-modify));
templates2events("/etc/dovecot/master.users",qw( email-update sogo-modify));
templates2events("/etc/dovecot/dovecot.conf",qw( sogo-modify));
templates2events("/etc/sogo/sieve.creds",qw(sogo-modify post-install bootstrap-console-save));

safe_symlink("sigusr1", "root/etc/e-smith/events/sogo-modify/services2adjust/httpd-e-smith");
safe_symlink("restart", "root/etc/e-smith/events/sogo-modify/services2adjust/sogod");
safe_symlink("restart", "root/etc/e-smith/events/sogo-modify/services2adjust/dovecot");
safe_symlink("restart", "root/etc/e-smith/events/sogo-modify/services2adjust/memcached");
safe_symlink("adjust", "root/etc/e-smith/events/sogo-modify/services2adjust/masq");
safe_symlink("restart", "root/etc/e-smith/events/sogo-modify/services2adjust/tinydns");
safe_symlink("start", "root/etc/e-smith/events/sogo-modify/services2adjust/mysql.init");


for my $event (qw(pre-backup))
{
    event_link("sogo-backup", $event, "80");
}
event_link("sogo-delete-user", "user-delete", "10");

panel_link("sogo", "manager");
